doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        default_table_options:
            row_format: DYNAMIC
        types:
            product_id: 'App\Cart\IdType'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
            Cart:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Cart'
                prefix: 'App\Cart'
                alias: Cart
            Product:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Cart'
                prefix: 'App\Cart'
                alias: Product
