# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    cart.storage.session_key: cart

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    cart.storage.session:
        class: App\Cart\Storage\SessionStorage
        arguments:
            $sessionKey: '%cart.storage.session_key%'
#            $_em: '@doctrine.orm.entity_manager'
    cart.storage.db:
        class: App\Cart\Storage\DBStorage
#        arguments:
#            $_em: '@doctrine.orm.entity_manager'

    cart.storage.memory:
        class: App\Cart\Storage\MemoryStorage


    App\Cart\Storage\StorageInterface: '@cart.storage.hibridStorage'

    cart.storage.hibridStorage:
        class: App\Cart\Storage\HybridStorage
        arguments:
            $from: '@cart.storage.session'
            $to: '@cart.storage.db'

    cart.calculator:
        class: App\Cart\Cost\SimpleCost
    App\Cart\Cost\CalculatorInterface: '@cart.calculator'

    cart:
        class: App\Cart\Cart
        autowire: false
        arguments:
            $calculator:
                - '@cart.calculator'

    cartItem:
        class: App\Cart\CartItem
        autowire: false

    App\Cart\CartEntityListener:
        tags:
            - { name: 'doctrine.orm.entity_listener', event: 'preUpdate', entity: 'App\Cart\Cart' }
            - { name: 'doctrine.orm.entity_listener', event: 'postLoad', entity: 'App\Cart\Cart' }
